---
describe: field
name: project_name
type: string
value: ""
primary: true
---
describe: field
name: well_known_statuses
type: array_ProjectIssueConfig_Well_known_statuses
value: "[]"
---
describe: field
name: well_known_labels
type: array_ProjectIssueConfig_Well_known_labels
value: "[]"
---
describe: field
name: exclusive_label_prefixes
type: array_primitive_string
value: "[]"
---
describe: field
name: well_known_prompts
type: array_ProjectIssueConfig_Well_known_prompts
value: "[]"
---
describe: field
name: default_prompt_for_developers
type: integer
value: 0
---
describe: field
name: default_prompt_for_users
type: integer
value: 0
---
describe: field
name: canned_queries
type: array_ProjectIssueConfig_Canned_queries
value: "[]"
---
describe: field
name: default_col_spec
type: string
value: ""
---
describe: field
name: default_sort_spec
type: string
value: ""
---
describe: field
name: default_x_attr
type: string
value: ""
---
describe: field
name: default_y_attr
type: string
value: ""
---
